name: Deploy App

on:
  push:
    branches:
    - main

jobs: 
  create-deployment-artefatcs:
    name: Create deployment artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Compile css and javascript
        run: |
          npm install
          npm run prod

      - name: Config php 7.4
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml 

      - name: Install composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist