name: Deploy App

on:
  push:
    branches:
    - master

jobs: 
  create-deployment-artefatcs:
    name: Create deployment artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Compile css and javascript
        run: |
          npm install
          npm run prod 